# Site settings
baseurl = "//haphan.cf/"
languageCode = "en-us"
title = "A curious developer | haphan.cf"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "spf13"

[params]
    name = "Ha Phan"
    description = "Ha Phan journey with the tech"
    bio = "Software Engineer & Perfectionist"
    # Enter optionally your twitter account
    #twitter = "Your Twitter account"
    enableRSS = true

    # Integrate Javascript files or stylesheets by adding the url to the external assets or by
    # linking local files with their path relative to the static folder, e.g. "css/styles.css"
    customCSS = []
    customJS  = []

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = ""
    subscribe = ""
    # Pagination links
    olderPosts = ""
    newerPosts = ""
    readMore = ""
    copyright = ""
    # Sharing options and author information in posts
    aboutAuthor = ""
    tweet = ""
    share = ""
    # 404 page
    title404 = ""
    subtitle404 = ""

    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
    iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    #twitter  = "https://www.twitter.com/thanhha"
    githubalt   = "https://www.github.com/haphan"
    linkedin  = "https://www.linkedin.com/in/haphant"
